In [1]:
import pandas as pd # importando o pandas para manipularmos o dataset

from sklearn.model_selection import train_test_split # utilizado para o split entre treinamento e teste
from sklearn.neighbors import KNeighborsRegressor # KNN para regressão
from sklearn.ensemble import RandomForestRegressor # Random Forest para regressão
from sklearn.preprocessing import RobustScaler # utilizado para que todas as entradas estejam na mesma escala numérica

In [2]:
df_wine = pd.read_csv('http://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv', sep=';') # importando a base
df_wine

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

## Divisão entre treino e teste

In [3]:
# split entre treinamento e teste
X_train_wine, X_test_wine, y_train_wine, y_test_wine = train_test_split(df_wine.drop('quality', axis=1), # aqui informamos os atributos
                                                                        df_wine['quality'], # aqui informamos as labels e na mesma ordem dos atributos
                                                                        test_size=0.20, # informamos a porcentagem de divisão da base. Geralmente é algo entre 20% (0.20) a 35% (0.35)
                                                                        random_state=0) # aqui informamos um "seed". É um valor aleatório e usado para que alguns algoritmos iniciem de forma aleatória a sua divisão.

## Treinamento do modelo

In [4]:
modelo_knn = KNeighborsRegressor().fit(X_train_wine, y_train_wine)

In [5]:
modelo_knn.score(X_test_wine, y_test_wine)

0.06674854998294111

In [6]:
modelo_knn.predict(X_test_wine)

array([5.2, 4.6, 6.4, 5.4, 6. , 5.4, 5.6, 5.8, 5.6, 5.4, 5.4, 5.4, 5.6,
       5.8, 5. , 5.4, 6.6, 6.4, 6. , 5.4, 6.6, 6. , 5.8, 5.2, 5.4, 5. ,
       5.6, 5.8, 4.8, 6.2, 6.4, 5.2, 5.6, 5.4, 6.8, 6.2, 5.4, 5.6, 6.4,
       6. , 5.6, 6. , 5.8, 5.8, 5.2, 5.8, 4.6, 5.6, 5.4, 5.6, 6.4, 5.4,
       5.4, 6.6, 5.4, 5.4, 5.2, 5.4, 6.2, 5.2, 5. , 6. , 6. , 5.8, 5.2,
       5.6, 5.2, 6.2, 7.2, 6.8, 5. , 5. , 5.2, 5. , 5.8, 6.4, 5.2, 5.6,
       5.4, 5.8, 5.4, 5.4, 4.8, 6.2, 5.4, 5.4, 5. , 5.2, 5.6, 5.2, 5. ,
       5. , 5.8, 5.4, 4.4, 5. , 5.4, 5.6, 5.4, 5.6, 6.4, 5.6, 5.2, 5.8,
       5.6, 5.6, 5.6, 6.2, 6.4, 5.8, 5.6, 5. , 6.6, 5.6, 5.4, 5.8, 5. ,
       6.2, 6.6, 5.8, 5. , 6.8, 5.2, 5.2, 6.2, 5. , 5.2, 5.2, 5.2, 5.8,
       5.4, 4.8, 5.2, 5.4, 6. , 5. , 5.8, 5. , 5.6, 5.8, 6.4, 5.4, 4.6,
       5.4, 5.2, 5.6, 6.6, 6.6, 6.2, 6. , 5.8, 5. , 6.2, 6. , 5.2, 5.8,
       5.6, 5.6, 5.6, 5.8, 5.8, 5.8, 5.4, 5.6, 5.6, 5. , 5.8, 5.8, 5.4,
       5.4, 5. , 5.6, 5.6, 6.4, 5.6, 5.6, 5.6, 7. , 6. , 5. , 5.2, 6.2,
       5.8, 5.6, 6. , 5.2, 5.6, 5.2, 5. , 5.6, 5.4, 5.2, 5.2, 5.4, 5. ,
       5.4, 5.4, 5. , 5.4, 5. , 5.8, 6.2, 5.8, 5.6, 5.2, 5.2, 5.6, 5.6,
       5.8, 5.2, 5.8, 5. , 4.8, 5.2, 5.8, 5.8, 5.2, 6. , 5.4, 5. , 5.6,
       5. , 5.8, 6. , 5.6, 5.4, 5.4, 5. , 5.6, 4.8, 5.2, 6.2, 5.2, 5.6,
       6.6, 6. , 6.2, 5.6, 5.6, 6.4, 5.6, 5.4, 5.6, 5.8, 5. , 5.2, 5.2,
       5.4, 4.8, 5.4, 5. , 6. , 4.8, 5.4, 5. , 5.2, 5. , 5.8, 5.2, 6.6,
       5.2, 6. , 5.8, 5.2, 5. , 4.6, 6. , 5.4, 5.6, 5. , 5. , 5.2, 5.6,
       5. , 7. , 5.8, 6. , 5.6, 6.4, 6.4, 5.8, 6.2, 5.2, 5.6, 5.2, 4.8,
       5.6, 5.4, 5.8, 5.8, 5.4, 5.6, 5.4, 6. , 4.8, 6.2, 5.2, 5.2, 5. ,
       5.4, 6.2, 4.6, 6.4, 5.2, 5.4, 6. , 5.2, 5.2, 5.6, 5. , 5.2, 6. ,
       5.4, 5.6, 5.6, 6.6, 5.2, 6. , 5.2, 7. ])

In [7]:
modelo_rf = RandomForestRegressor(random_state=0).fit(X_train_wine, y_train_wine)
modelo_rf.score(X_test_wine, y_test_wine)

0.4335142954622996

In [8]:
df_test = X_test_wine.copy() #pd.DataFrame(X_test_wine, columns=df_wine.drop('quality', axis=1).columns)
df_test['Quality_Real'] = y_test_wine.values
df_test['Quality_Predicao'] = modelo_rf.predict(X_test_wine)
df_test

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,Quality_Real,Quality_Predicao
1109,10.8,0.470,0.43,2.10,0.171,27.0,66.0,0.99820,3.17,0.76,10.8,6,5.38
1032,8.1,0.820,0.00,4.10,0.095,5.0,14.0,0.99854,3.36,0.53,9.6,5,4.79
1002,9.1,0.290,0.33,2.05,0.063,13.0,27.0,0.99516,3.26,0.84,11.7,7,6.97
487,10.2,0.645,0.36,1.80,0.053,5.0,14.0,0.99820,3.17,0.42,10.0,6,5.02
979,12.2,0.450,0.49,1.40,0.075,3.0,6.0,0.99690,3.13,0.63,10.4,5,5.17
...,...,...,...,...,...,...,...,...,...,...,...,...,...
794,10.1,0.270,0.54,2.30,0.065,7.0,26.0,0.99531,3.17,0.53,12.5,6,6.40
813,6.9,0.390,0.24,2.10,0.102,4.0,7.0,0.99462,3.44,0.58,11.4,4,5.92
1322,9.1,0.340,0.42,1.80,0.058,9.0,18.0,0.99392,3.18,0.55,11.4,5,6.48
704,9.1,0.765,0.04,1.60,0.078,4.0,14.0,0.99800,3.29,0.54,9.7,4,5.10
1023,8.2,0.320,0.42,2.30,0.098,3.0,9.0,0.99506,3.27,0.55,12.3,6,6.54